<script>                ::= <command> ';'?

<command>               ::= <simple command> | <pipeline>

<simple-command>        ::= "'"?<word>"'"? | '"'?<word>'"'? | <redirection> <simple-command>? | <simple-command> <redirection>

<pipeline>              ::= <command> '|' <command>

<redirection>           ::= '<' "'"?<word>"'"? | '>' '"'?<word>'"'? |'2>' "'"?<word>"'"? | '2>' '"'?<word>'"'?

<word>                  ::= <string> { <string> }? | <variable>

<variable>              ::= '$'<string>

// <string>                ::= "'"? <character>{ <character> }? "'"? | '"'? <character>{ <character> }? '"'?

// <identifier>            ::= <capital character> { <capital character> }?

// 얘네는 tokenize할 때만 필요함.
// <character>             ::= <capital letter> | <small letter> | <number> | <metacharacter> | <other ASCII character>

// <capital letter>        ::= 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' | 'K' | 'L' | 'M' | 'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T' | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z'

// <small letter>          ::= 'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z'

// <number>                ::= '0' | '1' | '2' | 3' | '4' | '5' | '6' | '7' | '8' | '9'

// <metacharacter>         ::= '-' | '|' | '&' | ';' | '(' | ')' | '<' | '>' | { spaces }

// <other ASCII character> ::= { ASCII characters }

// redirection rule 다시 짜기.
// pipeline이랑 redirection 조화를 잘... 어떻게...

// 이것은 예시일 뿐이다.
// 진짜 .bnf는 서브젝트에 맞게 적절하게 작성할 것.
