<script>                ::= <simple command> | <pipeline> | <logical expression>

<simple-command>        ::= "'"?<word>"'"? { "'"?<word>"'"? }? | '"'?<word>'"'? { '"'?<word>'"'? }? | <redirection> <simple-command>? | <simple-command> <redirection>

<pipeline>              ::= <simple-command> | <simple-command> '|' <pipeline>

<logical-expression>    ::= <simple-command> <logical-expression> | <logical-symbol> <simple-command> <logical-expression>?

<redirection>           ::= '<' "'"?<word>"'"? | '<' '"'?<word>'"'? | '>' "'"?<word>"'"? | '>' '"'?<word>'"'? | '2>' "'"?<word>"'"? | '2>' '"'?<word>'"'?

<word>                  ::= (?(STRING))? | (?<variable>)?

<variable>              ::= '$'(STRING)

<logical-symbol>        ::= '&&' | '||'


<script>: raw shell script (line)
<command>: simple command or pipeline
<simple-command>: 단어 한 개 이상. 따옴표로 묶여있을 수도 있음.(따옴표가 허용된다는 뜻)(따옴표로 묶여있다면 단어라는 뜻)
<pipeline>: 파이프 기호로 구분된 명령어들.
<redirection>: 리다이렉션 기호 뒤 또는 앞에 단어가 있어야 함.
<word>: 그냥 문자열 또는 변수.
<variable>: 문자열 앞에 달러 기호가 있어야 함.

(할당 연산자 어떻게 함)
	(실행부에서 함)
